### PR TITLE
daily rebuild

### PR DESCRIPTION
**Pull request by dominikwilkowski**
Hey,

This is the daily deploy script that will rebuild the DS every night at 12/1AM (depending on daylight savings).
Merge this when the color PR has been merged and you are live. Not before.

### CODE REVIEW

**Comment by dominikwilkowski** [comment]
@alex-page please merge this to the color branch

**Comment by pattyde** [comment]
@alex-page did you find out from @dominikwilkowski if we can merge this into the `feature/colours` branch?

**Comment by dominikwilkowski** [comment]
tots!

**Comment by dominikwilkowski** [comment]
(ups)

**Pull request merged**
