### PR TITLE
Added script to createDirectory across platforms

### PR DESCRIPTION
**Pull request by adamzerella**
As pointed out by @svict4 here: https://github.com/govau/designsystem/issues/136#issuecomment-434144399 a user cannot currently build the design system site on a Windows machine due to a `mkdir` command in our `package.json`. This PR addresses that by creating a `mkdir.js` helper function when running the build steps

### CODE REVIEW

**Comment by alex-page** [comment]
Use `mkdirp` you are creating technical debt - yikes

**Comment by adamzerella** [comment]
@alex-page I would usually agree but I feel like there is unnecessary overhead by adding `mkdirp`. I would say this is a simple function that shouldn't need any more maintenance than `mkidrp` considering they are basically doing the exact same thing: https://github.com/substack/node-mkdirp/blob/master/index.js#L71

I have noticed though that we don't need to create the `src/assets/js` folder as it's in currently in source control so this should only need to create one folder.

**Comment by alex-page** [comment]
The assets css and js files are built sometimes. The reason the css folder is in source control is that it contains libraries that do not work in some browsers so we intentionally let those files fail and the other css files continue working.

I understand your thinking however instead of reading mkdirp docs I have to read code. If you want to do it this way you should probably write tests as well and at that point it should probably be its own npm module. 

The argument that it is doing the exact thing is probably more of a reason to use the package aswell. There are a lot of simple npm packages I would install instead of writing myself as they are tested and used by multiple developers.

It is awesome though how easy it is to write something like mkdirp.

**Comment by adamzerella** [comment]
@alex-page @svict4 After a bit of discussion it seems that `mkdirp` is the more popular choice for fixing this issue. I'm closing this PR in favour of https://github.com/govau/designsystem/pull/303

**Pull request closed without merging**
