### PR TITLE
Add illustrations, consistency enhancements

### LINKED ISSUE #65: Add illustrations to the remaining pages on the documentation site
Each of the illustrations below needs to have their colours updated to match the new colour palette. They can then be added to the appropriate page on the documentation site.

- [x] Get started
- [x] Community
- [x] Support

screen_shot_2017-11-29_at_2 40 00_pm

### PR DESCRIPTION
**Pull request by Xochi**
fixes #65

### CODE REVIEW

**Comment by alex-page** [comment]
@Xochi this looks good, I did some work to remove a bunch of unnecessary classes and the abstract component ( whatever that was 😬 ). Let me know what you think.

**Comment by alex-page** [comment]
Thanks to @Xochi pointing out inconsistencies, I have made a bunch of changes:
- Use the default heading style, if we feel it's too intense maybe we should change it in the component
- Updated the homepage into tiers, removed a bunch of unnecessary spacing
- Updated the homepage components to be more DRY, statistics now uses feature
- Renamed a bunch of files with confusing names `promo` and `features`
- Moved helper functions outside of the `layout` directory
- Changed the key from `download` to `downloads` in the fetched data
- Changed the title from `what makes our components great` -> `what is in our system`, change the blurb underneath to be more consistent
- Minor bug fixes, clean up released component map

**Comment by sukhrajghuman** [comment]
Oh wow nice work ! the picture on the /404 page and /get-started page are the same. is that okay?

**Comment by alex-page** [comment]
No problem for me, the picture works for both. I don't think the 404 page is a huge priority as well 👍

**Pull request merged**
