### PR TITLE
Removed aria-selected from headergovau__bar as best practice

### PR DESCRIPTION
**Pull request by adamzerella**
This PR removes the `aria-selected` attribute from the `headergovau-accordion` element in an effort to implement best aria practice.  Following best practice, as the current `<a>` element doesn't actually link anywhere, it should technically be a button as outlined by Sarah Pulis an accessibility expert.

Additionally, I've removed some unused imports.

We should also look at what this means for the https://github.com/govau/uikit  accordion module.

### CODE REVIEW

**Comment by sukhrajghuman** [comment]
hmm i'm not sure that this role is valid in this case. From my understanding `role="tablist"` is used on a div that is a container for tabs. A good example is the "Write" and "Preview" tabs when you write a github comment. The buttons in this container would then have a `role="tab"`.

<image src="https://user-images.githubusercontent.com/20184809/47623831-da944800-db69-11e8-94e1-5f8e85af4630.png" width="500" />


Maybe we can bring this up in tomorrows a11y meetup.

**Comment by adamzerella** [comment]
@sukhrajghuman Good pickup, I've revised the role to be `presentation` and `link` respectivly, following: https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html

Also removed unused imports

**Comment by adamzerella** [comment]
@sukhrajghuman I've modified this commit to just removed the `aria-selected` for the time being. I think we won't merge this until we fix it at the uikit source.

We already have a issue raised for this: https://github.com/govau/uikit/issues/395 but we need to note that we will also change the `<a/>` to `<button/>` and we'll research removing `aria-selected`.

**Comment by alex-page** [comment]
Good work and problem solving @adamzerella and @sukhrajghuman really happy with how you both worked on this PR!

We will get 395 fixed up soon!

**Pull request closed without merging**
