### PR TITLE
Added meta descriptions to all page templates

### PR DESCRIPTION
**Pull request by adamzerella**
This PR adds a `<meta name="description">` tags to all HTML page templates in an effort to address site SEO and PWA improvements

### CODE REVIEW

**Comment by sukhrajghuman** [comment]
I think this is really important man. Good pick up. This is googles description of what goes below the link? I think the descriptions should be different for each page (About, Download, Components, Get Started etc). And they should also include key words.

For example the Get Started pages should include words like "get started, designer, developer, npm, component etc. " 

Because right now if I accept this PR the google description for each Design System search result will be something like the below:

<image src="https://user-images.githubusercontent.com/20184809/47623199-7752e780-db62-11e8-9a34-2cbe103efd43.png" width="800" />

**Comment by sukhrajghuman** [comment]
Actually, now that I think about it, a lot of the pages use the same layout. For example, all of the getting started docs use the `src/layout/getstarted/page.js`. And I think each different page should have its own unique meta description, just like the `<title>`. So we might need to pass front matter in each page of the site to put in the description.

Right now Google just uses the first chunk of text for each page for the description. I think for most pages this is pretty good. Maybe we can sit down and discuss?

**Comment by adamzerella** [comment]
@sukhrajghuman I've revised the PR to utilise the already present descriptions found in: `src/layout/page.js`. This PR also adds a default `<meta description>` to the `src/page.js`

**Comment by sukhrajghuman** [comment]
Assuming this PR is just adding the meta descriptions to all children pages of `/components`  this is good with me

**Comment by alex-page** [comment]
Great work @adamzerella and @sukhrajghuman nice simple but great for the user improvement to the site!

**Pull request merged**
